
const TABLES = [
  "IDMP_CUST_PROF",
  "IDMP_APP_IN_HIST",
  "CMP_OB_RESPONSE_D",
  "CMP_BRANCH_RESPONSE_D",
  "CMP_CAMPAIGN_MASTER",
  "CMP_CAMPAIGN_HIST",
  "IDMP_CUST_CONSENT",
  "IDMP_DMP_PROF",
  "IDMP_DMP_AUD",
  "IDMP_CONTACT_HISTORY",
  "IDMP_RESPONSE_HISTORY",
  "IDMP_EMAIL_SEND",
  "IDMP_EMAIL_OPEN",
  "IDMP_EMAIL_CLICK",
  "IDMP_EMAIL_BOUNCE" ];

module.exports = { TABLES };
